### ISSUE TITLE
ut61e+

### ISSUE THREAD

**Issue by kris0725pl** [prickle/UT61E-Multimeter#1]
hi, add support for ut61e+ over bluetooth adapter. 
i purchase this device:
https://meters.uni-trend.com/product/ut-d-series/

but your app not working. please add this device for support.

i create port com for bluetooth adapter. connected but not receiving data.

![Bez tytułu](https://github.com/user-attachments/assets/7858560e-7c23-4154-9ea7-617d9770b8ba)

**Comment by prickle** [comment]
Hi! It must have a different protocol. Does it work over regular wired serial?

**Comment by prickle** [comment]
The protocol is different, and would seem to have been partially decoded [here](https://github.com/ljakob/unit_ut61eplus/blob/af8df0259629519d2246762bdc9aa3f5fb4ccb41/ut61eplus/ut61eplus.py#L9). However this is for the HID connection over USB, the bluetooth connection protocol will have differences for sure. 

Of course, I would need a ut61e+ and the bluetooth dongle to be able to develop this feature myself and I have neither. Are you able to capture a dump of the serial stream? That would be a good first step to reversing the protocol.

**Comment by kris0725pl** [comment]
NO,over usb DONT work fine. Over bluetooth adapter not work.  I m ready to sniffer bluetooth :) but tell me what i do? Any program? What program is for sniffing bluetooth?  I have my youtube channel and i can rwcord video etc

**Comment by kris0725pl** [comment]
Sorry.. over usb not working to.   The protocol is different, and would seem to have been partially decoded  github.com here . However this is for the HID connection over USB, the bluetooth connection protocol will have differences for sure. Of course, I would need a ut61e+ and the bluetooth dongle to be able to develop this feature myself and I have neither. Are you able to capture a dump of the serial stream? That would be a good first step to reversing the protocol. —  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .  You are receiving this because you authored the thread. Message ID:  &lt;prickle/UT61E-Multimeter/issues/1/2497122182 @ github . com&gt;

**Comment by prickle** [comment]
No, USB would be a big effort. I have no practice with HID programming in Windows, and would need to implement the USBHID interface and a new parser.

But bluetooth might be easier, if it is presenting a serial interface.

Please try using a serial terminal program to read data from the serial port the dongle uses. You could then capture, save buffer or copy paste that data depending on the serial terminal's capabilities. You should see repeating sequences of bytes (about 20?) representing packets of binary data. Post here a short example of what you find and we will try to figure out if it's similar to what is already known about the protocol.

Cheers!

**Comment by kris0725pl** [comment]
Ok, i try capture over usb adapter for ut61e+ some data and paste it .

**Comment by kris0725pl** [comment]
Hi, i found on eevblog this thread:
https://www.eevblog.com/forum/projects/uni-t-ut-d07a-bluetooth/

I cant sniff ftom this device data. Maybe this will be help for you.

If you add this device to your program over blueyooth you will be king :)

**Comment by prickle** [comment]
Good find, lots of info. 

Unfortunately the posters say the bluetooth module is the newer BLE type, and it uses the GATT extension for discovery and communication, and has a totally different protocol. This would require an even bigger effort than USB! Like writing a whole new program from the beginning. And most certainly I would need an UT61E+ with bluetooth adapter myself to make it work.

Sorry my friend, it would appear there is no easy way to do this. For all intents and purposes, UT61E+ is a completely different meter from the UT61E and nothing I have done here can work with the newer meter.

Perhaps the best way to get my program to work for you is to get yourself the good old UT61E with the serial cable. I chose that meter because it is quite inexpensive and well suited for this specific purpose. Plus, we can never have too many meters, right?

Cheers!
